spring.application.name=pdf2questao

server.port=8080

spring.datasource.url=jdbc:sqlite:pdf2questao.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

springdoc.swagger-ui.path=/swagger-ui.html
